export const RANDOMIZE_LIST = 'RANDOMIZE_LIST'
export const START_BUBBLE_SORT = 'START_BUBBLE_SORT';
export const SORTING_START = 'SORTING_START';
export const SORTING_END = 'SORTING_END';

export const UPDATE_LIST = 'UPDATE_LIST';

export const SPEED_CHANGE = 'SPEED_CHANGE';

export const STOP_SORTING = 'STOP_SORTING';